# Generated by Django 4.1.7 on 2023-04-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='last_name',
        ),
    ]
